import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';

export function Disclaimer() {
  return (
    <Box sx={{ mt: 2 }}>
      <Typography variant="h5" color="inherit" noWrap>
        Disclaimer
      </Typography>
      <Typography variant="p" color="inherit" className="wrap-text">
        The passwords generated by this have not been verified to be sufficiently random.
        As such they may have a tendency to not be well distributed, or favor certain characters over others.
        This means that while they me be vulnerable to statistical attacks allowing discovery of their value without access to your private key.
        Additionally, the message being signed is consistent.
        This means any other dapp could ask you to sign the same message and use that response to generate these same passwords.
        Be careful what you sign.
        Lastly, because these passwords are generated off of the same seed, it is feasible that someone could guess your signature value given an output password
        and the parameters passed into it.
        This would result in all of your other passwords being leaked as well.
        Use at your own risk!
        The code for this project is available at <a href="https://github.com/trustborder/web3-password-manager">https://github.com/trustborder/web3-password-manager</a>.
        The algorithm used to generate passwords is subject to change without warning.
      </Typography>
    </Box>
  );
}

